### ISSUE TITLE
大佬你好，我在opqbot运行之后要怎么修改运行机器人呢?能出一个详细点的教程吗？

### ISSUE THREAD

**Issue by sayri23** [Leslie-Lin/chenruibot#1]
。

**Comment by sayri23** [comment]
运行在ide里运行会有下边红字
========= RESTART: C:\Users\ccc\Desktop\chenruibot-master\myqqbot.py =========
Traceback (most recent call last):
  File "C:\Users\ccc\Desktop\chenruibot-master\myqqbot.py", line 8, in <module>
    import text
  File "C:\Users\ccc\Desktop\chenruibot-master\text.py", line 4, in <module>
    from method import notice,ownthink,calculate,ya,keai,shadiao,send
  File "C:\Users\ccc\Desktop\chenruibot-master\method\ownthink.py", line 4, in <module>
    from method.send import send
  File "C:\Users\ccc\Desktop\chenruibot-master\method\send.py", line 5, in <module>
    setting=json.load(file_setting)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 2 column 22 (char 23)

**Comment by Leslie-Lin** [comment]
报错的原因我猜应该是因为根目录里的配置文件config.json里没填内容
我强烈建议你根据OPQBot的pythonsdk自己从头写一个机器人，只把陈睿的method文件夹的包抄去，陈睿主体部分的代码很臭，是我刚学python时的练习项目。method文件夹里的包至少应该可以正常运行

sayri23 <notifications@github.com> 于2021年2月20日周六 上午6:32写道：
